application:
  name: docker-simple-example-laravel
  project: my-laravel-app-cloud
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
- type: mysql
  version: "8.0"
  name: my-mysql-6132005
routers:
- name: main
  routes:
  - application_name: docker-simple-example-laravel
    paths:
    - /*
